//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BundleARMACommands {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BundleARMACommands.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBA_fnc_.
        /// </summary>
        public static string CBAAppend {
            get {
                return ResourceManager.GetString("CBAAppend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td[@class=&apos;IEntry&apos;].
        /// </summary>
        public static string CBARegex {
            get {
                return ResourceManager.GetString("CBARegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cbateam.github.io/CBA_A3/docs/index/Functions.html.
        /// </summary>
        public static string CBAUrl {
            get {
                return ResourceManager.GetString("CBAUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a != b,! a,a != b,a % b,a &amp;&amp; b,a &amp;&amp; b,a * b,a / b,a : b,a = b,a == b,a greater b,a greater= b,a hash b,a less b,a less= b,a or b,a ^ b,+,-.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[contains(@id, &apos;mw-pages&apos;)]//li[not(contains(@class, &apos;bohemia-header-nav-item&apos;))].
        /// </summary>
        public static string FunctionsRegex {
            get {
                return ResourceManager.GetString("FunctionsRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://community.bistudio.com/wiki/Category:Functions.
        /// </summary>
        public static string FunctionsUrl {
            get {
                return ResourceManager.GetString("FunctionsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&quot; /&gt;.
        /// </summary>
        public static string KeywordAppend_AutoComplete {
            get {
                return ResourceManager.GetString("KeywordAppend.AutoComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/Keywords&gt;.
        /// </summary>
        public static string KeywordAppend_SyntaxHighlighting {
            get {
                return ResourceManager.GetString("KeywordAppend.SyntaxHighlighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \t\t&lt;KeyWord name=\&quot;.
        /// </summary>
        public static string KeywordPrepend_AutoComplete {
            get {
                return ResourceManager.GetString("KeywordPrepend.AutoComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Keywords name=&quot;Keywords{0}&quot;&gt;.
        /// </summary>
        public static string KeywordPrepend_SyntaxHighlighting {
            get {
                return ResourceManager.GetString("KeywordPrepend.SyntaxHighlighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _exception,_forEachIndex,_this,_thisArgs,_thisEvent,_thisEventHandler,_thisFSM,_thisScript,_thisScriptedEventHandler,_time,_x,_y.
        /// </summary>
        public static string Prepend {
            get {
                return ResourceManager.GetString("Prepend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[contains(@id, &apos;mw-pages&apos;)]//li[not(contains(@class, &apos;bohemia-header-nav-item&apos;))].
        /// </summary>
        public static string ScriptingCommandsRegex {
            get {
                return ResourceManager.GetString("ScriptingCommandsRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://community.bistudio.com/wiki/Category:Scripting_Commands.
        /// </summary>
        public static string ScriptingCommandsUrl {
            get {
                return ResourceManager.GetString("ScriptingCommandsUrl", resourceCulture);
            }
        }
    }
}
